# Generated by Django 3.2.7 on 2021-12-26 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('jan', models.IntegerField(default=13, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(13)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
