# Generated by Django 3.2.7 on 2021-12-27 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='jan',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(13)]),
        ),
    ]
