# Generated by Django 3.2.7 on 2021-12-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0002_alter_mobiles_jan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='jan',
            field=models.CharField(max_length=13),
        ),
    ]
